#!/usr/bin/perl

use Artemus5;

my $t = [ '?', 'Hola: ', [ 'env', 'HOME' ], '$0',
	' Adios: ', 2, [ '=', 'test', 'value' ],
	[ 'test' ], '%arch', [ 'VERSION_STR' ] ];

my $a = Artemus5->new();

#my $src = '? "thi\"s stri\nng" that $0 { env "HOME" } %var';
my $src = '? "Hola: " { env "HOME" } $0 VERSION { = "test" "value" } %arch VERSION_STR';

my $c = $a->compile_c(\$src);

print $a->exec($c, 666), "\n";

