PREFIX=/usr/local

install:
	install -o root -g root -m 755 littool $(PREFIX)/bin
	install -o root -g root -m 755 -d $(PREFIX)/share/littool
	install -o root -g root -m 644 confs/*.conf $(PREFIX)/share/littool
